insert into CAR_MODEL (id, car_model, brand_id) values (1, 'MKS', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (2, 'Passat', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (3, 'STS', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (4, 'Astro', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (5, 'Maxima', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (6, 'Miata MX-5', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (7, 'Continental Flying Spur', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (8, 'Freelander', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (9, 'Grand Prix', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (10, 'Oasis', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (11, 'FX', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (12, 'Civic Si', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (13, 'Savana 1500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (14, 'Suburban 2500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (15, 'Roadmaster', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (16, 'Elan', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (17, 'V8 Vantage S', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (18, 'Malibu', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (19, 'H3T', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (20, 'LS', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (21, 'Focus', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (22, 'F-Series', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (23, 'Rondo', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (24, 'Cayenne', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (25, 'DBS', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (26, 'Boxster', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (27, 'Passport', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (28, 'M-Class', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (29, '370Z', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (30, 'RX', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (31, 'LTD Crown Victoria', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (32, 'SLK55 AMG', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (33, 'H2 SUV', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (34, 'Shadow', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (35, 'Crown Victoria', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (36, 'Econoline E350', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (37, 'Previa', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (38, 'Suburban 2500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (39, 'Durango', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (40, '7 Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (41, 'Canyon', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (42, 'E350', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (43, 'Q', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (44, 'Fleetwood', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (45, 'DTS', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (46, 'Ram 3500 Club', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (47, 'NSX', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (48, 'Optima', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (49, '550', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (50, 'L-Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (51, 'Miata MX-5', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (52, '599 GTB Fiorano', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (53, 'Express 2500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (54, 'LeMans', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (55, 'Aurora', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (56, 'Grand Prix', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (57, 'Sonata', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (58, 'Escort', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (59, 'Golf', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (60, 'Volt', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (61, 'Corvette', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (62, 'Endeavor', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (63, 'Mountaineer', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (64, 'Tucson', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (65, 'Samurai', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (66, 'Express 3500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (67, 'i-Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (68, 'Outback', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (69, 'Rendezvous', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (70, 'Ram Wagon B150', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (71, 'Tribute', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (72, 'S4', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (73, 'C70', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (74, 'Allroad', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (75, 'Achieva', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (76, 'Civic', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (77, '4Runner', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (78, 'SL-Class', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (79, 'Coupe GT', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (80, 'Breeze', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (81, 'Monterey', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (82, 'Bronco', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (83, 'Corsica', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (84, 'R32', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (85, 'Sonoma', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (86, 'CR-V', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (87, 'Ram Van B150', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (88, 'Rendezvous', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (89, '600', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (90, 'Jetta', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (91, '323', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (92, 'CX-9', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (93, 'Continental', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (94, '9-3', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (95, 'F150', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (96, 'Explorer', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (97, 'Rainier', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (98, 'A6', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (99, 'Torino', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (100, 'Model T', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (101, 'Highlander', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (102, 'GT500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (103, 'Colorado', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (104, 'Trans Sport', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (105, '458 Italia', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (106, 'Yukon XL 1500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (107, 'M3', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (108, 'Tiguan', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (109, 'Aero 8', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (110, 'Quattroporte', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (111, '164', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (112, 'Beretta', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (113, 'Metro', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (114, 'Cube', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (115, 'Malibu', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (116, 'CR-V', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (117, 'Spirit', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (118, '7 Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (119, 'Montero', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (120, 'Scoupe', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (121, 'MX-3', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (122, 'Camaro', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (123, 'Durango', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (124, '900', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (125, 'Grand Prix', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (126, 'Town & Country', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (127, 'M3', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (128, 'M5', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (129, 'Ram Van B350', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (130, 'xB', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (131, 'Eclipse', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (132, 'TSX', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (133, 'Liberty', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (134, 'Savana 3500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (135, 'Vantage', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (136, 'Highlander', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (137, 'Eldorado', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (138, 'Riviera', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (139, 'S40', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (140, 'S40', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (141, 'Allante', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (142, 'F250', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (143, 'Cordia', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (144, 'Tiguan', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (145, 'X6', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (146, 'Ram 3500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (147, 'Mark VIII', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (148, 'CL-Class', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (149, 'F150', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (150, 'GTI', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (151, 'B-Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (152, 'Golf', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (153, 'ES', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (154, 'Impreza', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (155, '9-3', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (156, 'A8', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (157, 'M6', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (158, 'Colt Vista', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (159, 'Excursion', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (160, 'Focus', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (161, 'Fox', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (162, 'Sebring', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (163, 'Suburban 2500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (164, 'Azera', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (165, 'Silverado 2500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (166, 'Esperante', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (167, 'Millenia', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (168, 'Freestar', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (169, 'Tahoe', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (170, 'Galant', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (171, 'Murano', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (172, 'Ram Van 1500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (173, 'Mustang', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (174, 'LX', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (175, 'Accord', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (176, 'Prizm', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (177, 'Continental Mark VII', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (178, 'Yukon XL 1500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (179, 'Santa Fe', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (180, 'Ram Van B150', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (181, 'LHS', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (182, '3500', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (183, 'Mustang', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (184, 'Mustang', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (185, 'M3', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (186, 'Express 1500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (187, 'X5', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (188, 'Mariner', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (189, 'Aerostar', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (190, 'Vision', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (191, 'S80', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (192, 'LX', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (193, 'RX', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (194, 'Caprice Classic', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (195, '1500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (196, 'Golf', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (197, 'Silverado 1500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (198, 'Explorer', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (199, 'GTI', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (200, 'Corsica', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (201, '4Runner', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (202, 'Venture', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (203, 'Firebird Formula', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (204, 'Rally Wagon G2500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (205, 'Edge', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (206, 'Passat', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (207, 'Diamante', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (208, '2500 Club Coupe', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (209, 'CX-7', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (210, 'Altima', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (211, 'M-Class', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (212, 'Corvette', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (213, 'LHS', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (214, 'Terrain', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (215, 'LaCrosse', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (216, '3500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (217, '1500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (218, 'Vitara', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (219, 'SJ', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (220, 'Passat', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (221, 'Jetta', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (222, 'Sorento', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (223, 'Azure', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (224, 'ES', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (225, 'Navigator', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (226, 'Echo', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (227, 'Grand Marquis', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (228, 'Loyale', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (229, 'Veyron', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (230, 'Ranger', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (231, 'Navigator', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (232, 'Sequoia', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (233, 'Civic', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (234, 'Thunderbird', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (235, 'MR2', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (236, 'Avenger', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (237, 'Mazdaspeed6', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (238, 'Caliber', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (239, 'Passat', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (240, 'Pilot', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (241, 'MKS', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (242, 'MKS', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (243, 'RX Hybrid', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (244, '2500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (245, 'Excel', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (246, 'Escalade ESV', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (247, 'Truck', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (248, 'MDX', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (249, 'Grand Cherokee', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (250, 'Range Rover Classic', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (251, 'Esprit', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (252, 'Concorde', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (253, 'S4', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (254, 'Discovery', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (255, 'TL', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (256, 'Murano', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (257, 'Seville', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (258, 'LeBaron', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (259, '626', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (260, '1 Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (261, 'XL-7', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (262, 'Thunderbird', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (263, 'CX-5', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (264, 'Miata MX-5', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (265, 'X5 M', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (266, 'SL-Class', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (267, 'Savana 1500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (268, '929', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (269, 'Town & Country', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (270, 'Blazer', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (271, 'Probe', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (272, 'Quattroporte', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (273, 'Bronco', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (274, 'tC', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (275, 'Legend', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (276, 'Challenger', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (277, 'Skylark', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (278, 'CTS', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (279, 'C30', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (280, 'H2', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (281, 'Mirage', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (282, '88', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (283, 'Corvette', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (284, '2500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (285, 'Acadia', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (286, 'XLR-V', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (287, 'i-350', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (288, 'T100 Xtra', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (289, 'Colt Vista', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (290, '929', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (291, 'CX-9', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (292, 'Legacy', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (293, 'S10', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (294, 'Lancer Evolution', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (295, 'Intrepid', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (296, 'Sierra 1500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (297, 'Fleetwood', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (298, 'Park Avenue', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (299, 'F350', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (300, 'Compass', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (301, 'Escape', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (302, 'Genesis Coupe', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (303, 'Suburban 1500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (304, 'XLR-V', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (305, 'Prizm', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (306, 'Astro', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (307, 'Tribeca', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (308, 'LeBaron', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (309, 'Sportage', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (310, 'SC', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (311, 'ES', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (312, 'V8', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (313, '3000GT', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (314, 'Bronco', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (315, 'Lancer', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (316, 'SVX', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (317, 'Passat', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (318, 'Grand Prix', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (319, 'Fury', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (320, 'Bonneville', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (321, 'Defender 90', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (322, 'E-Series', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (323, 'Riviera', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (324, 'Mighty Max', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (325, 'Cooper Countryman', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (326, 'B-Series', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (327, 'MPV', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (328, 'XJ', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (329, 'Grand Caravan', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (330, 'G35', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (331, 'Monte Carlo', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (332, 'H3T', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (333, 'V40', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (334, 'Jimmy', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (335, 'GT500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (336, '525', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (337, 'Accord', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (338, 'Dakota Club', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (339, 'A5', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (340, 'V40', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (341, 'Mazda6', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (342, 'Suburban 1500', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (343, 'RX', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (344, 'Elantra', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (345, '9-5', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (346, 'Tracer', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (347, 'Celica', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (348, 'TT', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (349, 'SC', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (350, 'S2000', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (351, '1500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (352, 'LX', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (353, 'Hombre', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (354, 'Spectra', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (355, 'X5', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (356, 'Town & Country', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (357, 'Yukon', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (358, 'XL-7', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (359, 'Rainier', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (360, 'Tacoma', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (361, 'Discovery', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (362, 'Club Wagon', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (363, 'Solstice', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (364, 'Prius c', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (365, '6 Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (366, 'Town Car', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (367, 'Eldorado', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (368, 'Sienna', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (369, 'MKX', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (370, 'Jimmy', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (371, 'Fiero', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (372, 'Escalade', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (373, 'Sienna', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (374, 'Achieva', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (375, 'Century', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (376, 'Sedona', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (377, 'GTI', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (378, 'Venture', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (379, 'Volare', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (380, 'Passat', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (381, 'Scirocco', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (382, 'S-Class', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (383, 'Baja', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (384, 'F350', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (385, 'Pajero', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (386, 'VUE', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (387, 'Camry Hybrid', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (388, 'Explorer', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (389, '7 Series', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (390, 'Q7', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (391, 'Countach', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (392, 'Quattro', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (393, 'Vanquish S', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (394, 'J', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (395, 'M5', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (396, 'Grand Prix', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (397, 'G8', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (398, 'Blackwood', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (399, 'Navigator', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (400, 'Previa', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (401, '7 Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (402, 'Sienna', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (403, 'VehiCROSS', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (404, 'Discovery Series II', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (405, 'D250', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (406, 'M-Class', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (407, '57', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (408, 'Silverado 1500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (409, 'Yukon', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (410, 'Element', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (411, 'Outback', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (412, 'GT-R', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (413, 'Protege', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (414, 'Express', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (415, 'Concorde', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (416, 'Tempo', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (417, 'Silverado 1500', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (418, 'Talon', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (419, 'E-Class', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (420, 'Parisienne', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (421, 'V12 Vantage', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (422, '745', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (423, 'Ram 1500 Club', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (424, 'Electra', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (425, 'Canyon', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (426, 'New Beetle', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (427, 'Nubira', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (428, 'Classic', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (429, 'M5', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (430, 'Jetta', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (431, 'Stratus', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (432, 'CTS', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (433, 'Xterra', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (434, 'Silverado 1500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (435, 'Sigma', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (436, 'Pacifica', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (437, 'MX-5', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (438, '200', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (439, 'Prius Plug-in Hybrid', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (440, 'DB9', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (441, 'Camry', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (442, 'Continental', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (443, 'New Beetle', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (444, 'MX-6', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (445, 'Land Cruiser', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (446, 'Continental', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (447, 'RAV4', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (448, 'Sonata', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (449, 'Jetta', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (450, 'Grand Caravan', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (451, 'XK Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (452, 'Villager', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (453, '626', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (454, 'H2', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (455, 'Expo', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (456, 'Grand Vitara', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (457, 'E-Series', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (458, '88', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (459, 'XJ Series', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (460, '400SE', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (461, 'CLK-Class', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (462, 'Vanquish S', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (463, 'E250', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (464, 'Savana 2500', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (465, 'LeSabre', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (466, 'Bravada', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (467, 'G5', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (468, 'Neon', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (469, 'R32', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (470, 'RX Hybrid', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (471, 'S80', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (472, 'Legend', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (473, 'Tacoma', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (474, 'Safari', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (475, 'Talon', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (476, 'Corvette', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (477, '9000', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (478, 'S-Class', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (479, 'S90', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (480, 'V8 Vantage', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (481, 'Golf', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (482, 'Diablo', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (483, 'Rio', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (484, 'Silhouette', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (485, 'XLR', 2);
insert into CAR_MODEL (id, car_model, brand_id) values (486, 'J', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (487, 'XL-7', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (488, 'GX', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (489, '57', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (490, 'Viper', 1);
insert into CAR_MODEL (id, car_model, brand_id) values (491, 'Range Rover', 5);
insert into CAR_MODEL (id, car_model, brand_id) values (492, 'Sable', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (493, 'Avalanche', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (494, 'Ram Van B150', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (495, 'Sportvan G20', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (496, 'Accord Crosstour', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (497, 'Century', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (498, '300ZX', 3);
insert into CAR_MODEL (id, car_model, brand_id) values (499, 'Blazer', 4);
insert into CAR_MODEL (id, car_model, brand_id) values (500, 'Sedona', 4);
